### PR TITLE
add handful commands

### PR DESCRIPTION
**Pull request by flowerett**

### CODE REVIEW

**Comment by flowerett** [comment]
### testing rails_restart:
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
27670 deploy    20   0  397056 200420   9928 S  0.0  9.8   0:06.72 Passenger AppPreloader: /srv/www/back_end_api/current
27688 deploy    20   0  735660 244456   4740 S  0.0 11.9   0:05.26 Passenger RubyApp: /srv/www/back_end_api/current (staging)
27698 deploy    20   0  735756 234312   4636 S  0.0 11.4   0:02.19 Passenger RubyApp: /srv/www/back_end_api/current (staging)
27709 deploy    20   0  735852 233268   4652 S  0.0 11.4   0:02.13 Passenger RubyApp: /srv/www/back_end_api/current (staging)
27720 deploy    20   0  735948 233056   4636 S  0.0 11.4   0:02.13 Passenger RubyApp: /srv/www/back_end_api/current (staging)
```
```deploy@chronos:/srv/www/back_end_api/current$ bundle exec rake rails_restart```
```
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
29246 deploy    20   0  744520 234180   4308 S 25.3 11.4   0:01.53 Passenger RubyApp: /srv/www/back_end_api/current (staging)
29257 deploy    20   0  744616 234292   4304 S 25.3 11.4   0:01.37 Passenger RubyApp: /srv/www/back_end_api/current (staging)
29225 deploy    20   0  744328 235040   4164 S 25.0 11.5   0:01.83 Passenger RubyApp: /srv/www/back_end_api/current (staging)
29235 deploy    20   0  744424 234316   4304 S 24.6 11.4   0:01.67 Passenger RubyApp: /srv/www/back_end_api/current (staging)
29193 deploy    20   0  406752 204700   9928 S  0.0 10.0   0:06.73 Passenger AppPreloader: /srv/www/back_end_api/current
```

**Comment by flowerett** [comment]
### testing sidekiq stop:
```
deploy@chronos:/srv/www/back_end_api/current$ bundle exec rake stop_sidekiq
deploy@chronos:/srv/www/back_end_api/current$ ls tmp/pids
deploy@chronos:/srv/www/back_end_api/current$
```

**Comment by flowerett** [comment]
### testing sidekiq start:
```
deploy@chronos:/srv/www/back_end_api/current$ bundle exec rake start_sidekiq
-----> Start sidekiq
```
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
29777 deploy    20   0  975740 198152   9432 S  6.5  9.7   0:05.97 sidekiq 4.0.1 back_end_api [0 of 25 busy]
```

**Comment by flowerett** [comment]
restart failed:
```deploy@chronos:/srv/www/back_end_api/current$ bundle exec rake restart_sidekiq
rake aborted!
NameError: undefined local variable or method `stop_sidekiq' for main:Object```

**Comment by flowerett** [comment]
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
27537 deploy    20   0  970456 200980   6876 S  0.0  9.8   0:05.83 sidekiq 4.0.1 back_end_api [0 of 25 busy]
```
```
deploy@theia:/srv/www/back_end_api/current$ bundle exec rake restart_sidekiq
-----> Stop sidekiq
Sidekiq shut down gracefully.
-----> Start sidekiq
```
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
28417 deploy    20   0  970416 200436   6876 S  0.3  9.8   0:05.57 sidekiq 4.0.1 back_end_api [0 of 25 busy]
```

**Comment by flowerett** [comment]
need review :)

**Comment by rubyengineer** [comment]
:ok let's try

**Pull request merged**
